version: '3'
services:
  libros:
    container_name: libros
    build: .
    image: node:18-alpine3.18
    command: npm run start
    ports:
      - "${PORT:-9090}"
    environment:
      DB_PORT: your_db_port
      DB_HOST: db
      DB_USER: your_db_user
      DB_NAME: your_db_name
      DB_PASSWORD: your_db_password
      PORT: "${PORT:-9090}"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      DB_PORT: your_db_port
      DB_HOST: db
      DB_USER: your_db_user
      DB_NAME: your_db_name
      DB_PASSWORD: your_db_password
volumes:
  db-data: 
